#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
export PLUGIN_PATH=${PLUGIN_PATH:="/var/lib/dokku/plugins"}
export DOKKU_ROOT=${DOKKU_ROOT:="/home/dokku"}

case "$1" in
  receive)
    APP="$2"; IMAGE="app/$APP.$BRANCH"; export BRANCH="$3";
    echo "-----> Building $APP from branch $BRANCH ..."
    cat | dokku build $APP $IMAGE
    echo "-----> Releasing $APP ..."
    dokku release $APP $IMAGE $BRANCH
    echo "-----> Deploying $APP ..."
    dokku deploy $APP $IMAGE $BRANCH
    echo "-----> Cleaning up ..."
    dokku cleanup
    echo "=====> Application deployed:"
    echo "       $(dokku url $APP $BRANCH)"
    echo
    ;;

  build)
    APP="$2"; IMAGE="$3"; CACHE_DIR="$DOKKU_ROOT/$APP/cache";
    id=$(cat | docker run -i -a stdin ginlane/buildstep /bin/bash -c "mkdir -p /app && tar -xC /app")
    test $(docker wait $id) -eq 0
    docker commit $id $IMAGE > /dev/null
    id=$(docker run -d $IMAGE /build/detector)
    docker attach $id
    test $(docker wait $id) -eq 0
    docker commit $id $IMAGE > /dev/null
    [[ -d $CACHE_DIR ]] || mkdir $CACHE_DIR
    pluginhook pre-build $APP $IMAGE $BRANCH
    # id=$(docker run -d $IMAGE /build/builder)
    id=$(docker run -d -v $CACHE_DIR:/cache $IMAGE /build/builder)
    docker attach $id
    test $(docker wait $id) -eq 0
    docker commit $id $IMAGE > /dev/null
    ;;

  release)
    APP="$2"; IMAGE="$3";
    pluginhook pre-release $APP $IMAGE $BRANCH
    if [[ -f "$DOKKU_ROOT/$APP/$BRANCH.ENV" ]]; then
      id=$(cat "$DOKKU_ROOT/$APP/$BRANCH.ENV" | docker run -i -a stdin $IMAGE /bin/bash -c "mkdir -p /app/.profile.d && cat > /app/.profile.d/app-env.sh")
      test $(docker wait $id) -eq 0
      docker commit $id $IMAGE > /dev/null
    fi
    pluginhook post-release $APP $IMAGE $BRANCH
    ;;

  deploy)


    # APP="$2"; IMAGE="$3";
    # pluginhook pre-deploy $APP $IMAGE $BRANCH
    # if [[ ! -f "$DOKKU_ROOT/$APP/$BRANCH.PORT" ]]; then
    #   # First deploy
    #   id=$(docker run -d -p 5000 -e PORT=5000 $IMAGE /bin/bash -c "/start web")
    #   echo $id > "$DOKKU_ROOT/$APP/$BRANCH.CONTAINER"
    #   port=$(docker port $id 5000 | sed 's/0.0.0.0://')
    #   echo $port > "$DOKKU_ROOT/$APP/$BRANCH.PORT"
    #   echo "http://$(< "$HOME/HOSTNAME"):$port" > "$DOKKU_ROOT/$APP/$BRANCH.URL"
    #   pluginhook post-first-deploy $APP $IMAGE $BRANCH
    # else
    #   # Regular deploy
    #   oldid=$(< "$DOKKU_ROOT/$APP/$BRANCH.CONTAINER")
    #   docker kill $oldid > /dev/null
    #   port=$(< "$DOKKU_ROOT/$APP/$BRANCH.PORT")
    #   id=$(docker run -d -p ":$port" -e "PORT=$port" $IMAGE /bin/bash -c "/start web")
    #   echo $id > "$DOKKU_ROOT/$APP/$BRANCH.CONTAINER"
    # fi
    # pluginhook post-deploy $APP $IMAGE $BRANCH $port


    APP="$2"; IMAGE="$3"
    pluginhook pre-deploy $APP $IMAGE $BRANCH

    FIRSTDEPLOY=0
    # kill the app when running
    if [[ -f "$DOKKU_ROOT/$APP/$BRANCH.PORT" ]]; then
      oldid=$(< "$DOKKU_ROOT/$APP/$BRANCH.CONTAINER")
      docker kill $oldid > /dev/null
    else
      # run post-first-deploy to begin with
      FIRSTDEPLOY=1
    fi

    # start the app
    id=$(docker run -d -p 5000 -e PORT=5000 $IMAGE /bin/bash -c "/start web")
    echo $id > "$DOKKU_ROOT/$APP/CONTAINER"
    port=$(docker port $id 5000 | sed 's/0.0.0.0://')
    echo $port > "$DOKKU_ROOT/$APP/$BRANCH.PORT"
    echo "http://$(< "$DOKKU_ROOT/HOSTNAME"):$port" > "$DOKKU_ROOT/$APP/$BRANCH.URL"

    if [[ $FIRSTDEPLOY == 1 ]]; then
      pluginhook post-first-deploy $APP $IMAGE $BRANCH
    fi

    #pluginhook post-deploy $APP $port
    pluginhook post-deploy $APP $IMAGE $BRANCH $port

    ;;

  cleanup)
    # delete all non-running container
    docker ps -a | grep 'Exit' |  awk '{print $1}' | xargs docker rm &> /dev/null &
    # delete unused images
    docker images | grep '<none>' |  awk '{print $3}'  | xargs docker rmi &> /dev/null &
    ;;

  plugins)
    ls -1 -d $PLUGIN_PATH/*/
    ;;

  plugins-install)
    pluginhook install
    ;;

  # temporary hack for https://github.com/progrium/dokku/issues/82
  deploy:all)
    for app in $(ls -d $DOKKU_ROOT/*/); do
      APP=$(basename $app);
      IMAGE="app/$APP"
      dokku deploy $APP $IMAGE
    done
    ;;

  help)
    cat<<EOF | pluginhook commands help | sort
    help            Print the list of commands
    plugins         Print active plugins
    plugins-install Install active plugins
EOF
    ;;

  *)
    pluginhook commands "$@"
    ;;

esac
