#!/usr/bin/env bash
set -e
set -o pipefail
export PLUGIN_PATH=${PLUGIN_PATH:="/var/lib/dokku/plugins"}
case "$1" in
  receive)
    APP="$2"; BRANCH="$3"; IMAGE="app/$APP.$BRANCH"; 
    echo "-----> Building $APP from branch $BRANCH ..."
    cat | dokku build $APP $IMAGE
    echo "-----> Build complete!"
    echo "-----> Releasing $APP ..."
    dokku release $APP $IMAGE $BRANCH
    echo "-----> Release complete!"
    echo "-----> Deploying $APP ..."
    dokku deploy $APP $IMAGE $BRANCH
    echo "-----> Deploy complete!"
    echo "-----> Cleaning up ..."
    dokku cleanup
    echo "-----> Cleanup complete!"
    echo "=====> Application deployed:"
    echo "       $(dokku url $APP $BRANCH)"
    echo
    ;;

  build)
    APP="$2"; IMAGE="$3";
    id=$(cat | docker run -i -a stdin ginlane/buildstep /bin/bash -c "mkdir -p /app && tar -xC /app")
    test $(docker wait $id) -eq 0
    docker commit $id $IMAGE > /dev/null
    pluginhook pre-build $APP $IMAGE
    id=$(docker run -d $IMAGE /build/builder)
    docker attach $id
    test $(docker wait $id) -eq 0
    docker commit $id $IMAGE > /dev/null
    ;;

  release)
    APP="$2"; IMAGE="$3"; BRANCH="$4";
    pluginhook pre-release $APP $IMAGE
    if [[ -f "$HOME/$APP/$BRANCH.ENV" ]]; then
      id=$(cat "$HOME/$APP/$BRANCH.ENV" | docker run -i -a stdin $IMAGE /bin/bash -c "mkdir -p /app/.profile.d && cat > /app/.profile.d/app-env.sh")
      test $(docker wait $id) -eq 0
      docker commit $id $IMAGE > /dev/null
    fi
    pluginhook post-release $APP $IMAGE
    ;;

  deploy)
    APP="$2"; IMAGE="$3"; BRANCH="$4";
    pluginhook pre-deploy $APP $IMAGE
    if [[ ! -f "$HOME/$APP/$BRANCH.PORT" ]]; then
      # First deploy
      id=$(docker run -d -p 5000 -e PORT=5000 $IMAGE /bin/bash -c "/start web")
      echo $id > "$HOME/$APP/$BRANCH.CONTAINER"
      port=$(docker port $id 5000)
      echo $port > "$HOME/$APP/$BRANCH.PORT"
      echo "$(< "$HOME/HOSTNAME"):$port" > "$HOME/$APP/$BRANCH.ADDRESS"
    else
      # Regular deploy
      oldid=$(< "$HOME/$APP/$BRANCH.CONTAINER")
      docker kill $oldid > /dev/null
      port=$(< "$HOME/$APP/$BRANCH.PORT")
      id=$(docker run -d -p ":$port" -e "PORT=$port" $IMAGE /bin/bash -c "/start web")
      echo $id > "$HOME/$APP/$BRANCH.CONTAINER"
    fi
    pluginhook post-deploy $APP $port $BRANCH
    ;;

  cleanup)
    # delete all non-running container
    docker ps -a | grep 'Exit' |  awk '{print $1}' | xargs docker rm &> /dev/null &
    # delete unused images
    docker images | grep '<none>' |  awk '{print $3}'  | xargs docker rmi &> /dev/null &
    ;;

  plugins)
    ls -1 -d $PLUGIN_PATH/*/
    ;;

  plugins-install)
    pluginhook install
    ;;

  # temporary hack for https://github.com/progrium/dokku/issues/82
  deploy:all)
    for app in $(ls -d $HOME/*/); do
      APP=$(basename $app);
      IMAGE="app/$APP"
      dokku deploy $APP $IMAGE
    done
    ;;

  help)
    cat<<EOF | pluginhook commands help | sort
    help            Print the list of commands
    plugins         Print active plugins
    plugins-install Install active plugins
EOF
    ;;

  *)
    pluginhook commands "$@"
    ;;

esac
