#!/bin/bash
set -e; 
case "$1" in
  url)  
    if [[ -f "/home/git/$2/$3.VHOST" ]]; then
      echo "$(< "/home/git/$2/$3.VHOST")"
    else
      cat
    fi
    ;;

  help) cat && cat<<EOF
    url <app>       Show the URL for an application
EOF
    ;;

esac
cat
