#!/bin/bash
# Check if name is specified and exists
if [[ $1 == rails:* ]]; then
  if [[ -z $2 ]]; then
    echo "You must specify an app name"
    exit 1
  else
    APP="$2"; IMAGE="$3"; APP_IMAGE=`echo $IMAGE | cut -d '/' -f 2`; BRANCH="$4";  # disregard app/ part of $IMAGE
    if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
      echo "App $APP does not exist"
      exit 1
    fi
    buildpack=$(docker run $IMAGE cat /buildpack_name)
    if [[ $buildpack == "Ruby" ]]; then
      # echo $@
      case "$1" in
        rails:db:create)
          if ! docker run $IMAGE cat /app/Gemfile | grep -q -e "'pg'" -e '"pg"'; then
            # add 'pg' gem to Gemfile
            echo
            echo "No pg gem found in the Gemfile -- please add gem 'pg' and redeploy"
            echo
            exit 1
          fi
          # always use pgsql on rails apps
          dokku postgresql:create $APP $IMAGE
        ;;
        rails:db:migrate)
          docker run -t $IMAGE /bin/bash -c "export HOME=/app; for file in /app/.profile.d/*; do source \$file; done; hash -r; cd /app; RAILS_ENV=production rake db:migrate"
          sleep 1
        ;;
        rails:db:seed)    
          docker run -t $IMAGE /bin/bash -c "export HOME=/app; for file in /app/.profile.d/*; do source \$file; done; hash -r; cd /app; RAILS_ENV=production rake db:seed"
          sleep 1
        ;;
        rails:assets:precompile)    
          docker run -t $IMAGE /bin/bash -c "export HOME=/app; for file in /app/.profile.d/*; do source \$file; done; hash -r; cd /app; RAILS_ENV=production rake assets:precompile"
          sleep 1
        ;;
        rails:mount:public)
          echo "in empty rails:mount:public"
          # HOST_DIR="/var/lib/docker/volumes/public-$APP_IMAGE"
          # CONTAINER_DIR="/app/public"
          # RENAMED_VOLUME="$MOUNT_DIR/layer:/app/public"

          # oldid=$(< "$HOME/$APP/$BRANCH.CONTAINER")
          # docker kill $oldid > /dev/null

          # port=$(< "$HOME/$APP/$BRANCH.PORT")

          # # test $(docker wait $id) -eq 0
          # sleep 4
          # if [[ ! -d $HOST_DIR ]]; then
          #   id=$(docker run -d -v $CONTAINER_DIR -p ":$port" -e "PORT=$port" $IMAGE /bin/bash -c "/start web")
          #   # docker kill $id > /dev/null
          #   VOLUME_PATH=$(docker inspect $id | grep "/var/lib/docker/volumes/" | awk '{print $2}' | sed -e"s/\/layer//" | sed -e's/"//g')
          #   mv $VOLUME_PATH $HOST_DIR
          #   # id=$(docker run -d -v $RENAMED_VOLUME -p ":$port" -e "PORT=$port" $IMAGE /bin/bash -c "/start web")
          # else
          #   id=$(docker run -d -v $HOST_DIR:$CONTAINER_DIR:rw -p ":$port" -e "PORT=$port" $IMAGE /bin/bash -c "/start web")
          # fi
          # sleep 1

          # echo $id > "$HOME/$APP/$BRANCH.CONTAINER"
        ;;
      esac
    fi
  fi
fi

if [[ $1 == help ]]; then
  cat && cat<<EOF
    rails:db:create <app> <image>     Create rails DB for the app
    rails:db:migrate <app> <image>     Migrate rails DB for the app
    rails:db:seed <app> <image>     Seed rails DB for the app
    rails:mount:public <app> <image>     Mount rails public directory to host OS
EOF
fi

cat
