#!/bin/bash
# Check if name is specified and exists
if [[ $1 == rails:* ]]; then
  if [[ -z $2 ]]; then
    echo "You must specify an app name"
    exit 1
  else
    APP="$2"; IMAGE="app/$APP"; 
    if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
      echo "App $APP does not exist"
      exit 1
    fi
    buildpack=$(docker run $IMAGE cat /buildpack_name)
    if [[ $buildpack == "Ruby" ]]; then
      case "$1" in
        rails:db:create)
          if ! docker run $IMAGE cat /app/Gemfile | grep -q -e "'pg'" -e '"pg"'; then
            echo
            echo "No pg gem found in the Gemfile -- please add gem 'pg' and redeploy"
            echo
            exit 1
          fi
          # always use pgsql on rails apps
          dokku postgresql:create $APP
        ;;
        rails:db:migrate)
          docker run -t $IMAGE /bin/bash -c "export HOME=/app; export CURL_TIMEOUT=120; for file in /app/.profile.d/*; do source \$file; done; hash -r; cd /app; RAILS_ENV=production rake db:migrate"
          sleep 1
        ;;
        rails:db:seed)    
          docker run -t $IMAGE /bin/bash -c "export HOME=/app; export CURL_TIMEOUT=120; for file in /app/.profile.d/*; do source \$file; done; hash -r; cd /app; RAILS_ENV=production rake db:seed"
          sleep 1
        ;;
        rails:assets:precompile)
          id=$(docker run -d $IMAGE /bin/bash -c "export HOME=/app; export CURL_TIMEOUT=120; for file in /app/.profile.d/*; do source \$file; done; hash -r; cd /app; RAILS_ENV=production rake assets:precompile")
          docker attach $id
          test $(docker wait $id) -eq 0
          docker commit $id $IMAGE > /dev/null
          sleep 1
        ;;
        rails:mount:public)
          echo "in empty rails:mount:public"
        ;;
      esac
    fi
  fi
fi

if [[ $1 == help ]]; then
  cat && cat<<EOF
    rails:db:create <app> <image>     Create rails DB
    rails:db:migrate <app> <image>     Migrate rails DB
    rails:db:seed <app> <image>     Seed rails DB
    rails:db:precompile <app> <image>     Precompile assets
    rails:mount:public <app> <image>     Mount rails public directory to host OS
EOF
fi

cat
