#!/bin/bash
#set -e; 

# Check if name is specified and exists
if [[ $1 == rails:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
	APP="$2"; IMAGE="$3"
    	if [[ ! -d "/home/git/$APP" ]]; then
            echo "App $APP does not exist"
            exit 1
    	fi
    fi
fi

case "$1" in
    rails:migrate)
	   docker run -t $IMAGE /bin/bash -c "export HOME=/app; for file in /app/.profile.d/*; do source \$file; done; hash -r; cd /app; RAILS_ENV=production rake db:migrate"
	   sleep 1
    ;;
    help)
        cat && cat<<EOF
    rails:migrate <app>     Migrate rails DB for the app
    rails:dbcreate <app>     Create rails DB for the app
EOF
    ;;
esac
cat
